spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true